---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-proxy-config
  namespace: registry-proxy
data:
  config.yaml: |
    enabled: true
    proxies:
        docker.cloudsmith.io: hub.cicd.getdeepin.org
        docker.io: hub.cicd.getdeepin.org
        gcr.io: gcr.cicd.getdeepin.org
        ghcr.io: ghcr.cicd.getdeepin.org
        k8s.gcr.io: k8s-gcr.cicd.getdeepin.org
        quay.io: quay.cicd.getdeepin.org
        registry.k8s.io: k8s-registry.cicd.getdeepin.org
        hub.deepin.com: deepinhub.cicd.getdeepin.org
    excludeNamespaces:
        - "registry-proxy"
        - "default"
    includeNamespaces:
        - '*'
    includeRegistries:
        - "docker.io"
        - "ghcr.io"
        - "gcr.io"
        - "k8s.gcr.io"
        - "registry.k8s.io"
        - "quay.io"
        - "docker.cloudsmith.io"
        - "hub.deepin.com"
