---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/displayName: ''
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: gotify2matrix-bot
  name: gotify2matrix-bot
  namespace: rsshub
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: gotify2matrix-bot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: gotify2matrix-bot
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: gotify2matrix-conf
          image: larshaalck/gotify2matrix
          imagePullPolicy: IfNotPresent
          name: gotify-matrix-bot
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /session
              name: gotify2matrix
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gotify2matrix
          persistentVolumeClaim:
            claimName: gotify2matrix
