apiVersion: apps/v1
kind: Deployment
metadata:
   name: worker-deployment-1
spec:
   replicas: 1
   selector: 
     matchLabels:
        app: obsworkerappname
   template:
     metadata:
       labels:
         app: obsworkerappname
     spec:
       containers:
       - name: test-worker-pod
         command: ["/bin/bash"]
         args: ["-c", "sleep 1d  && echo Sleep expired > /dev/termination-log"]
         image: registry.opensuse.org/obs/server/2.10/containers/containers/openbuildservice/backend:210
         imagePullPolicy: Never
         resources:
          limits:
            devices.kubevirt.io/kvm: "1"
          requests:
            cpu: 100m
            devices.kubevirt.io/kvm: "1"
         securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_NICE
          privileged: false
          runAsUser: 0
         volumeMounts:
              - name: boot-dir
                mountPath: /boot
              - name: modules-dir
                mountPath: /lib/modules
       volumes:
         - name: boot-dir
           hostPath:
             path: /boot
         - name: modules-dir
           hostPath:
             path: /lib/modules
       hostname: obs-worker-1
---
apiVersion: v1
kind: Service
metadata:
  name: myobsservice
  labels:
    servicename: obsworkerservicename
spec:
  selector:
    app: obsworkerappname
  type: NodePort
  externalTrafficPolicy: "Local"
  ports:
    - name: woker-1
      protocol: TCP
      port: 32515
      targetPort: 32515
      nodePort: 32315
    - name: woker-2
      protocol: TCP
      port: 32516
      targetPort: 32516
      nodePort: 32516
