apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    k8s.kuboard.cn/pvcType: Dynamic
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: nfs-rsshub
    volume.kubernetes.io/storage-provisioner: nfs-rsshub
  finalizers:
  - kubernetes.io/pvc-protection
  name: gotify-data
  namespace: rsshub
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rsshub
