---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: gotify
    meta.helm.sh/release-namespace: rsshub
  labels:
    app.kubernetes.io/instance: gotify
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gotify
    app.kubernetes.io/version: 2.4.0
    helm.sh/chart: gotify-0.3.0
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: gotify
  name: gotify
  namespace: rsshub
  resourceVersion: '251257110'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: gotify
      app.kubernetes.io/name: gotify
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: gotify
        app.kubernetes.io/name: gotify
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
            - name: GOTIFY_DATABASE_DIALECT
              value: sqlite3
            - name: GOTIFY_DEFAULTUSER_NAME
              value: admin
            - name: GOTIFY_DEFAULTUSER_PASS
              value: admin
            - name: GOTIFY_PASSSTRENGTH
              value: '10'
            - name: GOTIFY_UPLOADEDIMAGESDIR
              value: data/images
            - name: GOTIFY_PLUGINSDIR
              value: data/plugins
            - name: GOTIFY_REGISTRATION
              value: 'false'
          image: 'gotify/server:2.4.0'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: gotify
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/data
              name: gotify-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gotify
      serviceAccountName: gotify
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gotify-data
          persistentVolumeClaim:
            claimName: gotify-data
