---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ttrss
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: ttrss
  name: ttrss
  namespace: rsshub
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ttrss
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ttrss
    spec:
      containers:
        - env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ttrss-db
            - name: PGID
              value: '1000'
            - name: PUID
              value: '1000'
            - name: SELF_URL_PATH
              value: 'https://rsshub.cicd.getdeepin.org'
            - name: DB_HOST
              value: ttrss-postgres
          image: 'wangqiru/ttrss:nightly'
          imagePullPolicy: Always
          name: ttrss
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /var/www/feed-icons
              name: ttrss-feed-icons
            - mountPath: /var/www/plugins.local/gotify_notifications
              name: plugin-gotify
      dnsPolicy: ClusterFirst
      nodeSelector:
        nettype: optical-fiber
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
      volumes:
        - name: ttrss-feed-icons
          persistentVolumeClaim:
            claimName: ttrss-feed-icons
        - name: plugin-gotify
          persistentVolumeClaim:
            claimName: plugin-gotify

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ttrss
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: ttrss
  name: ttrss
  namespace: rsshub
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ttrss-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ttrss
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: ttrss
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: ttrss
  name: ttrss
  namespace: rsshub
spec:
  ingressClassName: traefik
  rules:
    - host: ttrss.cicd.getdeepin.org
      http:
        paths:
          - backend:
              service:
                name: ttrss
                port:
                  number: 80
            path: /
            pathType: Prefix
