---
apiVersion: v1
kind: Namespace
metadata:
  name: obs

---
# Obs storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backend-test
  namespace: obs
  labels:
    app: backend-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "obsbackend"
  resources:
    requests:
      storage: 2600Gi
  #volumeName: nfs-pv-obsbackend
