---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: frpc
    k8s.kuboard.cn/name: frpc
  name: frpc
  namespace: frp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frpc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frpc
    spec:
      containers:
        - image: hub.cicd.getdeepin.org/snowdreamtech/frpc
          imagePullPolicy: Always
          name: frpc
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/frp
              name: config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: frpc-config


