periodics:
- name: ci-triage-robot-close-prs
  interval: 6h
  decorate: true
  annotations:
    description: Closes rotten PRs after 90d of inactivity
    testgrid-tab-name: close-prs
  spec:
    containers:
    - image: hub.deepin.com/prow/commenter
      command:
      - commenter
      args:
      - |-
        --query=org:linuxdeepin
        org:deepin-community
        org:peeweep-test
        is:pr
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=2160h
      - --token=/etc/github-token/token
      - --endpoint=http://ghproxy
      - |-
        --comment=The Deepin project currently lacks enough active contributors to adequately respond to all issues and PRs.

        This bot triages PRs according to the following rules:
        - After 270d of inactivity, `lifecycle/stale` is applied
        - After 90d of inactivity since `lifecycle/stale` was applied, `lifecycle/rotten` is applied
        - After 90d of inactivity since `lifecycle/rotten` was applied, the PR is closed

        You can:
        - Reopen this PR with `/reopen`
        - Mark this PR as fresh with `/remove-lifecycle rotten`
        - Offer to help out with [Issue Triage][1]

        /close

      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/github-token
    volumes:
    - name: token
      secret:
        secretName: github-token
