---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: infra-settingsdeploy
spec:
  replicas: 1
  template:
    spec:
      repository: deepin-community/infra-settings
      labels:
      - infra-setting-runner
      hostAliases:
      - ip: "10.20.64.81"
        hostnames:
        - "github.com"
      - ip: "10.20.64.82"
        hostnames:
        - "api.github.com"
      - ip: "10.20.64.83"
        hostnames:
        - "github.githubassets.com"
      - ip: "10.20.64.84"
        hostnames:
        - "raw.githubusercontent.com"
      - ip: "10.20.64.85"
        hostnames:
        - "collector.github.com"
      - ip: "10.20.64.86"
        hostnames:
          - "avatars.githubusercontent.com"
      containers:
      - name: runner
        image: hub.deepin.com/deepincicd/github-runner-dind
        imagePullPolicy: Always

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: deepin-community-runners
spec:
  replicas: 2
  template:
    spec:
      organization: deepin-community
      hostAliases:
      - ip: "10.20.64.81"
        hostnames:
        - "github.com"
      - ip: "10.20.64.82"
        hostnames:
        - "api.github.com"
      - ip: "10.20.64.83"
        hostnames:
        - "github.githubassets.com"
      - ip: "10.20.64.84"
        hostnames:
        - "raw.githubusercontent.com"
      - ip: "10.20.64.85"
        hostnames:
        - "collector.github.com"
      - ip: "10.20.64.86"
        hostnames:
          - "avatars.githubusercontent.com"
      containers:
      - name: runner
        image: hub.deepin.com/deepincicd/github-runner-dind
        imagePullPolicy: Always

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: peeweep-test-runners
spec:
  replicas: 2
  template:
    spec:
      repository: peeweep-test/infra-settings
      hostAliases:
      - ip: "10.20.64.81"
        hostnames:
        - "github.com"
      - ip: "10.20.64.82"
        hostnames:
        - "api.github.com"
      - ip: "10.20.64.83"
        hostnames:
        - "github.githubassets.com"
      - ip: "10.20.64.84"
        hostnames:
        - "raw.githubusercontent.com"
      - ip: "10.20.64.85"
        hostnames:
        - "collector.github.com"
      - ip: "10.20.64.86"
        hostnames:
          - "avatars.githubusercontent.com"
      containers:
      - name: runner
        image: hub.deepin.com/deepincicd/github-runner-dind
        imagePullPolicy: Always
